# the BioSample accession
biosample_accession: SAMN40905419

# name of CSV file listing barcode runs to uploade
barcode_runs: ./barcode_runs_upload.csv

# the following come from the SRA FTP upload instructions
ftp_username: subftp
ftp_account_folder: uploads/tyler.n.starr_gmail.com_pVxU5Fx4

# Meaningful name for this sample's FTP folder:
ftp_subfolder: mAb_breadth_Overbaugh_v2
